name: PexActivityMonitor
version: 1.0
main: com.micx.PexActivityMonitor
api-version: 1.13
author: Micx
commands:
  weryfikacja:
    description: Sprawdza aktywność ekipy.
    usage: /weryfikacja
    permission: ekipa.info
  weryfikacjaweek:
    description: Sprawdza tygodniowy czas online i AFK.
    usage: /weryfikacjaweek
    permission: ekipa.info
permissions:
  ekipa.info:
    description: Uprawnienia do zarządzania aktywnością ekipy.
    default: op
